# Generated by Django 5.2.5 on 2025-08-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productstore',
            name='stock_non_negative',
        ),
        migrations.RenameField(
            model_name='productstore',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='productstore',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
